

USE RDS_TO_SNOWFLAKE_PIPELINE_DB;

USE SCHEMA RDS_TO_SNOWFLAKE_PIPELINE_SCHEMA;


COPY INTO "ALBUM"
FROM @RDS_TO_SNOWFLAKE_PIPELINE_STAGE/Album/
FILE_FORMAT = (FORMAT_NAME = 'RDS_TO_SNOWFLAKE_PIPELINE_PARQUET_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO "ARTIST"
FROM @RDS_TO_SNOWFLAKE_PIPELINE_STAGE/Artist/
FILE_FORMAT = (FORMAT_NAME = 'RDS_TO_SNOWFLAKE_PIPELINE_PARQUET_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO "CUSTOMER"
FROM @RDS_TO_SNOWFLAKE_PIPELINE_STAGE/Customer/
FILE_FORMAT = (FORMAT_NAME = 'RDS_TO_SNOWFLAKE_PIPELINE_PARQUET_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO "EMPLOYEE"
FROM @RDS_TO_SNOWFLAKE_PIPELINE_STAGE/Employee/
FILE_FORMAT = (FORMAT_NAME = 'RDS_TO_SNOWFLAKE_PIPELINE_PARQUET_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO "GENRE"
FROM @RDS_TO_SNOWFLAKE_PIPELINE_STAGE/Genre/
FILE_FORMAT = (FORMAT_NAME = 'RDS_TO_SNOWFLAKE_PIPELINE_PARQUET_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO "INVOICE"
FROM @RDS_TO_SNOWFLAKE_PIPELINE_STAGE/Invoice/
FILE_FORMAT = (FORMAT_NAME = 'RDS_TO_SNOWFLAKE_PIPELINE_PARQUET_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO "INVOICE_LINE"
FROM @RDS_TO_SNOWFLAKE_PIPELINE_STAGE/InvoiceLine/
FILE_FORMAT = (FORMAT_NAME = 'RDS_TO_SNOWFLAKE_PIPELINE_PARQUET_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO "MEDIA_TYPE"
FROM @RDS_TO_SNOWFLAKE_PIPELINE_STAGE/MediaType/
FILE_FORMAT = (FORMAT_NAME = 'RDS_TO_SNOWFLAKE_PIPELINE_PARQUET_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO "PLAYLIST"
FROM @RDS_TO_SNOWFLAKE_PIPELINE_STAGE/Playlist/
FILE_FORMAT = (FORMAT_NAME = 'RDS_TO_SNOWFLAKE_PIPELINE_PARQUET_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO "PLAYLIST_TRACK"
FROM @RDS_TO_SNOWFLAKE_PIPELINE_STAGE/PlaylistTrack/
FILE_FORMAT = (FORMAT_NAME = 'RDS_TO_SNOWFLAKE_PIPELINE_PARQUET_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO "TRACK"
FROM @RDS_TO_SNOWFLAKE_PIPELINE_STAGE/Track/
FILE_FORMAT = (FORMAT_NAME = 'RDS_TO_SNOWFLAKE_PIPELINE_PARQUET_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;


